- platform: group
  name: 'Tapparelle zona giorno'
  entities:
    - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level
    - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_2
    - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_3
    - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_4
    - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_5

- platform: group
  name: 'Tapparelle zona notte'
  entities:
    - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_6
    - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_7
    - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_8
    - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_9
    - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_10
