- platform: mqtt
  name: "Temperatura Arduino"
  state_topic: "sensor/temperature"
  qos: 0
- platform: mqtt
  name: "Umidità Arduino"
  state_topic: "sensor/humidity"
  qos: 0
- platform: time_date
  name: "Time"
- platform: time_date
  name: "Date"
  display_options:
    - 'date'
- platform: template
  sensors:
    holidays_calendar:
      friendly_name: 'Prossima Festività'
      value_template: '{{ states.calendar.festivita_in_italia.attributes.message }}'

- platform: template
  sensors:
    date_template:
      friendly_name: 'Data Formattata'
      value_template: '{{ as_timestamp(now()) | timestamp_custom("%d/%m/%Y", True) }}'

- platform: template
  sensors:
    indicatore_giorno_lavorativo:
      friendly_name: 'Giorno lavorativo'
      value_template: >
        {% if (is_state('binary_sensor.workday_sensor', 'on')) %}
         on
        {% else %}
         off
        {% endif %}
      icon_template: >
        {% if (is_state('binary_sensor.workday_sensor', 'on')) %}
         mdi:briefcase
        {% else %}
         mdi:emoticon
        {% endif %}

##########################################################
## HA Instance
##########################################################

- platform: command_line
  command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
  name: Versione HA Corrente
  scan_interval: 3600

- platform: version
  name: Versione HA installata

- platform: uptime
  
- platform: command_line
  name: CPU Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: command_line
  name: "HA Ultimo Riavvio"
  command: cat /proc/uptime | awk '{printf "%0.f", $1}'
  scan_interval: 60
  value_template: >-
    {% set uptime = value | int %}
    {% set seconds = uptime % 60 %}
    {% set minutes = ((uptime % 3600) / 60) | int %}
    {% set hours = ((uptime % 86400) / 3600) | int %}
    {% set days = (uptime / 86400) | int %}
    {%- if days > 0 -%}
      {%- if days == 1 -%}
        1 giorno
      {%- else -%}
        {{ days }} giorni
      {%- endif -%}
      {{ ', ' }}
    {%- endif -%}
    {{ '%02d' % hours }}:{{ '%02d' % minutes }}

- platform: systemmonitor
  resources:
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use

- platform: apcupsd
  resources:
    - bcharge
    - loadpct
    - status
    - timeleft
    - model
    - linev

- platform: template
  sensors:
    battery_sensore_camera_am:
      friendly_name: 'Sensore temp. camera AM' 
      unit_of_measurement: '%'
      value_template: >
          {%- if states.sensor.temperature_158d0002b548e2.attributes.battery_level %}
              {{ states.sensor.temperature_158d0002b548e2.attributes.battery_level|round }}
          {% else %}
              {{ states.sensor.temperature_158d0002b548e2.state }}
          {%- endif %}
      icon_template: '{%- if  states.sensor.temperature_158d0002b548e2.attributes.battery_level <= 5 %}mdi:battery-outline{%- elif states.sensor.temperature_158d0002b548e2.attributes.battery_level >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.sensor.temperature_158d0002b548e2.attributes.battery_level|float / 10)|round*10}}{%- endif %}'

- platform: template
  sensors:
    battery_sensore_esterno:
      friendly_name: 'Sensore temp. esterna' 
      unit_of_measurement: '%'
      value_template: >
          {%- if states.sensor.temperature_158d0002b54aa2.attributes.battery_level %}
              {{ states.sensor.temperature_158d0002b54aa2.attributes.battery_level|round }}
          {% else %}
              {{ states.sensor.temperature_158d0002b54aa2.state }}
          {%- endif %}
      icon_template: '{%- if  states.sensor.temperature_158d0002b54aa2.attributes.battery_level <= 5 %}mdi:battery-outline{%- elif states.sensor.temperature_158d0002b54aa2.attributes.battery_level >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.sensor.temperature_158d0002b54aa2.attributes.battery_level|float / 10)|round*10}}{%- endif %}'

- platform: template
  sensors:
    battery_sensore_camera_eli:
      friendly_name: 'Sensore temp. camera Eli' 
      unit_of_measurement: '%'
      value_template: >
          {%- if states.sensor.temperature_158d0002b6c54b.attributes.battery_level %}
              {{ states.sensor.temperature_158d0002b6c54b.attributes.battery_level|round }}
          {% else %}
              {{ states.sensor.temperature_158d0002b6c54b.state }}
          {%- endif %}
      icon_template: '{%- if  states.sensor.temperature_158d0002b6c54b.attributes.battery_level <= 5 %}mdi:battery-outline{%- elif states.sensor.temperature_158d0002b6c54b.attributes.battery_level >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.sensor.temperature_158d0002b6c54b.attributes.battery_level|float / 10)|round*10}}{%- endif %}'

- platform: template
  sensors:
    battery_sensore_zona_giorno:
      friendly_name: 'Sensore temp. zona giorno' 
      unit_of_measurement: '%'
      value_template: >
          {%- if states.sensor.temperature_158d0002b549c2.attributes.battery_level %}
              {{ states.sensor.temperature_158d0002b549c2.attributes.battery_level|round }}
          {% else %}
              {{ states.sensor.temperature_158d0002b549c2.state }}
          {%- endif %}
      icon_template: '{%- if  states.sensor.temperature_158d0002b549c2.attributes.battery_level <= 5 %}mdi:battery-outline{%- elif states.sensor.temperature_158d0002b549c2.attributes.battery_level >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.sensor.temperature_158d0002b549c2.attributes.battery_level|float / 10)|round*10}}{%- endif %}'
