- id: au_test_telegram_pingpong
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    - service: notify.Notifica_telegram
      data:
        message: 'pong'

- id: au_bot_motiondetection_enable
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/telecamereon'
  action:
    - service: switch.turn_on
      entity_id: switch.telecamera_garage_motion
    - service: notify.Notifica_telegram
      data:
        message: "Ho attivato il rilevamento dei movimenti in garage"

- id: au_bot_motiondetection_disable
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/telecamereoff'
  action:
    - service: switch.turn_off
      entity_id: switch.telecamera_garage_motion
    - service: notify.Notifica_telegram
      data:
        message: "Ho disattivato il rilevamento dei movimenti in garage"

- id: au_bot_offta1
  hide_entity: true
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/termoptoff'
    - platform: event
      event_type: telegram_callback
      event_data:
        command: '/termoptoff'
  action:
    - service: switch.turn_off
      entity_id: switch.80027536bcddc28a80b2
    - service: notify.Notifica_telegram
      data:
        message: "Ho spento il termoarrdeo del bagno al piano terra"

- id: au_bot_offta2
  hide_entity: true
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/termo1poff'
    - platform: event
      event_type: telegram_callback
      event_data:
        command: '/termo1poff'
  action:
    - service: switch.turn_off
      entity_id: switch.80027536807d3a4f32b3
    - service: notify.Notifica_telegram
      data:
        message: "Ho spento il termoarrdeo del bagno al 1 piano"

- id: au_bot_offta3
  hide_entity: true
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/termo1pvoff'
    - platform: event
      event_type: telegram_callback
      event_data:
        command: '/termo1pvoff'
  action:
    - service: switch.turn_off
      entity_id: switch.80027536b4e62d4206a5
    - service: notify.Notifica_telegram
      data:
        message: "Ho spento il termoarrdeo del bagno vasca"

- id: au_bot_cover_close
  hide_entity: true
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/chiuditapparelle'
  action:
    - service: cover.close_cover
      entity_id: cover.tapparelle_zona_giorno
    - service: cover.close_cover
      entity_id: cover.tapparelle_zona_notte
    - service: notify.Notifica_telegram
      data:
        message: "Ho chiusole tapparelle della casa"

- id: au_test_telegram_cmd
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/cmd'
  action:
    - service: notify.Notifica_telegram
      data_template:
        message: >
         Telecamere: \n
         /telecamereon - Attiva motion detection \n
         /telecamereoff - Disattiva motion detection \n
         Termoarredi: \n
         /termoptoff - Spegne termoarredo bagno PT \n
         /termo1poff - Spegne termoarredo bagno AM \n
         /termo1pvoff - Spegne termoarredo bagno Eli \n
         Tapparelle: \n
         /chiuditapparelle - Chiude tutte le tapparelle della casa
         Sistema: \n
         /ping - Test Connessione
